name: Linux Build gcc

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
    contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - run: sudo apt install -y automake libtool pkg-config libssl-dev libz-dev nasm

    - name: Checkout repository using checkout action v3.1.0
      uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8
      with:
        repository: intel/QAT_Engine

    - name: autogen
      run: ACLOCAL_PATH=/usr/share/aclocal ./autogen.sh

    - name: configure
      run: ./configure --with-qat_hw_dir=$PWD --with-openssl_install_dir=$PWD/openssl_install
    
    - name: make depend
      run: make depend

    - name: make
      run: make -j
